#Expyriment 1.0.0 (Python 3.12.7), .xpe-file, coding: UTF-8
#date: Wed Sep 24 2025 23:36:42
#sha1: a86fed
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Darwin', node='Saruhans-MacBook-Pro.local', release='24.6.0', version='Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6041', machine='arm64')
Time,Type,Event,Value,Detail,Detail2
1119,design,log,
#design: #exp: Week3-3
#design: block_cnt,block_id,trial_cnt,trial_id
1119,design,logged,
1119,Experiment,started
1119,Stimulus,presented,1
1119,Stimulus,presented,2
1119,Stimulus,presented,3
1119,Stimulus,presented,4
1127,Stimulus,presented,0
1627,stderr,received,'Traceback (most recent call last):'
1628,stderr,received,'  File "/Users/saru/Local_Work/cogsup/experimental_approach/cogsup-prog/Week-3/Exercises/kanizsa-rectangle.py", line 63, in <module>'
1628,stderr,received,'    kanizsa_rectangle(scaling=aspect, rec_scale=rec_sc,circ_scale=circ_sc)'
1628,stderr,received,'  File "/Users/saru/Local_Work/cogsup/experimental_approach/cogsup-prog/Week-3/Exercises/kanizsa-rectangle.py", line 47, in kanizsa_rectangle'
1628,stderr,received,'    control.start(subject_id=1)'
1628,stderr,received,'  File "/opt/anaconda3/lib/python3.12/site-packages/expyriment/control/_experiment_control.py", line 59, in start'
1629,stderr,received,'    raise Exception("Experiment is already started!")'
1629,stderr,received,'Exception: Experiment is already started!'
